// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8mJIo4a-tLnhr2tblBUJn-TgEsE3vVWM',
    appId: '1:924507937416:web:8fd0943d92e90591ef5d3d',
    messagingSenderId: '924507937416',
    projectId: 'kids-tell-d0ks8m',
    authDomain: 'kids-tell-d0ks8m.firebaseapp.com',
    storageBucket: 'kids-tell-d0ks8m.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE5VWehuvDsLdzT3FKKnWwrXBhIJ841vc',
    appId: '1:924507937416:android:b7d82266c8678a72ef5d3d',
    messagingSenderId: '924507937416',
    projectId: 'kids-tell-d0ks8m',
    storageBucket: 'kids-tell-d0ks8m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnKGE0X2Q5SBLDimKwd9ldmfSqtrUBTi0',
    appId: '1:924507937416:ios:9785c07c75e4b889ef5d3d',
    messagingSenderId: '924507937416',
    projectId: 'kids-tell-d0ks8m',
    storageBucket: 'kids-tell-d0ks8m.firebasestorage.app',
    iosBundleId: 'com.fairycraft.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8mJIo4a-tLnhr2tblBUJn-TgEsE3vVWM',
    appId: '1:924507937416:web:e7c1167aeac4bebbef5d3d',
    messagingSenderId: '924507937416',
    projectId: 'kids-tell-d0ks8m',
    authDomain: 'kids-tell-d0ks8m.firebaseapp.com',
    storageBucket: 'kids-tell-d0ks8m.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnKGE0X2Q5SBLDimKwd9ldmfSqtrUBTi0',
    appId: '1:924507937416:ios:1f7292d175bc426cef5d3d',
    messagingSenderId: '924507937416',
    projectId: 'kids-tell-d0ks8m',
    storageBucket: 'kids-tell-d0ks8m.firebasestorage.app',
    iosBundleId: 'com.example.kidsdom',
  );

}